name: "Cupypi Pypi Publish on Release"
description: "Publish your python project to pypi quickly. (On create new release)"
author: "GitLabBR"

inputs:
    username:
        type: string
        description: "Your pypi username"
        required: true
    password:
        type: string
        description: "Your pypi password"
        required: true

runs:
  using: node16
  main: dist/index.js
branding:
  icon: shield
  color: red
