name: "Cupypi Pypi Publish on Release"
description: "Publish your python project to pypi quickly. (On create new release)"
author: "GitLabBR"

inputs:
    username:
        type: string
        description: "Your pypi username"
        required: true
    password:
        type: string
        description: "Your pypi password"
        required: true

jobs:
    pip:
        runs-on: ubuntu-latest
        steps:
            - name: setup pip
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v1
            - uses: BSFishy/pip-action@v1
              with:
                  packages: |
                      twine
            - name: Upload dist   
              run: python -m twine upload dist/*


runs:
  using: node20
branding:
  icon: shield
  color: red
